export const LEGAL_UPDATED = '23 August 2026'
export const SUPPORT_MAIL = 'hello@orcha.app'
export const MODEL_PROVIDERS =
  'third-party model providers Orcha uses to generate a reply — not one vendor. Everyday and hard questions prefer a live free high-reasoning model when one exists (Ox Alpha via OpenRouter during its preview). Otherwise chat uses Google AI Studio (Gemini) and Groq free tiers. GPT-5.6 is only used when no such free model is live. Each provider processes prompts under its own terms and retention policy. OpenRouter states the Ox Alpha provider retains prompts and completions and does not use them for training'

export type LegalId = 'privacy' | 'terms' | 'delete'

export type LegalDoc = {
  id: LegalId
  title: string
  path: string
  sections: { heading: string; body: string }[]
}

export const LEGAL_DOCS: Record<LegalId, LegalDoc> = {
  privacy: {
    id: 'privacy',
    title: 'Privacy Policy',
    path: '/privacy',
    sections: [
      {
        heading: 'Who this covers',
        body: 'Orcha is a consumer AI company builder. This policy describes the current web prototype. It is written so the same practices can ship on the App Store and Google Play. We do not market Orcha to children.',
      },
      {
        heading: 'What stays on this device',
        body: 'Your name, email, companies, chats, settings, and any content reports are stored in this browser (localStorage). There is no Orcha account server in this prototype. Signing out locks the AI on this device; it does not upload a profile to us.',
      },
      {
        heading: 'What leaves this device',
        body: `When Cloud AI is on, the text of the chat you send — including custom instructions and the About you field — is sent to ${MODEL_PROVIDERS}. File attachments in this prototype send file names, not file contents. We do not sell data. We do not run ads. We do not use App Tracking Transparency tracking. This web preview may load fonts from Google Fonts, which can see your IP address.`,
      },
      {
        heading: 'AI-generated replies',
        body: 'Replies are generated by language models, not a person. They can be wrong. They are labeled Orcha · AI in the thread. You can turn off Cloud AI in Settings. When it is off, nothing is sent to any model provider and Orcha will not invent a live model reply.',
      },
      {
        heading: 'Age',
        body: 'You must be 13 or older to create an account. Orcha is not directed at children and is not in Apple’s Kids Category or Google Play’s Designed for Families program. We do not knowingly collect personal information from children under 13. If we learn we have, we delete it.',
      },
      {
        heading: 'Retention and deletion',
        body: 'Data stays on this device until you delete it. Delete all chats removes messages and keeps companies. Delete account removes the account, companies, chats, reports, and settings from this browser immediately. That is a real deletion, not a freeze. Google Play also requires a web path to request deletion; use /delete-account.',
      },
      {
        heading: 'Your choices',
        body: 'Turn off Cloud AI to stop sending chats to every model provider. Turn off Save chat history to stop writing new messages to this device. Export downloads a JSON copy of what is stored here. You can report an AI reply in the thread without leaving Orcha.',
      },
      {
        heading: 'Contact',
        body: `Questions: ${SUPPORT_MAIL}. A store listing must keep this address current. This prototype may store a support note on the device if mail is not configured.`,
      },
    ],
  },
  terms: {
    id: 'terms',
    title: 'Terms of Use',
    path: '/terms',
    sections: [
      {
        heading: 'The service',
        body: 'Orcha helps you start and run an AI company from chat. This prototype is provided as-is. Features labeled synthetic are previews, not live company metrics.',
      },
      {
        heading: 'Eligibility',
        body: 'You must be at least 13. If you are 13–17, you may use Orcha only with a parent or guardian’s permission where required by law.',
      },
      {
        heading: 'Accounts',
        body: 'The account in this prototype lives on your device. You can delete it in Settings. Do not use Orcha to collect personal data from children, to generate sexual content involving minors, or to plan crimes.',
      },
      {
        heading: 'AI output',
        body: 'Orcha replies are AI-generated. You are responsible for how you use them. Do not present them as human, as legal, medical, or financial advice, or as a live guarantee of a company result.',
      },
      {
        heading: 'Acceptable use',
        body: 'You may not use Orcha to create or seek child sexual abuse material, to exploit or endanger children, to generate scams or malware, or to violate another person’s rights. We block some of those prompts on the device and instruct the model to refuse the rest.',
      },
      {
        heading: 'Third-party AI',
        body: `Cloud replies are produced by ${MODEL_PROVIDERS}. Turning Cloud AI off stops that sharing with all of them.`,
      },
      {
        heading: 'Payments',
        body: 'Orcha Pro is $20 per month. This web prototype does not collect that payment. A future iOS or Android build that sells the subscription will use Apple In-App Purchase and Google Play Billing. It will not route around the stores.',
      },
      {
        heading: 'Contact',
        body: `Support: ${SUPPORT_MAIL}.`,
      },
    ],
  },
  delete: {
    id: 'delete',
    title: 'Delete your account',
    path: '/delete-account',
    sections: [
      {
        heading: 'In the app',
        body: 'Open Settings → Legal & Privacy → Delete account, or Settings → Data controls → Delete account. Confirm once. This removes the account, companies, chats, reports, and settings stored in this browser. Sign out is not deletion.',
      },
      {
        heading: 'If you cannot open Orcha',
        body: 'This prototype stores the account only on the device. Clear this site’s data in the browser, or delete the app and its local storage, to finish removal. When Orcha has a cloud account, this page will also accept an email deletion request.',
      },
      {
        heading: 'What we keep',
        body: 'Nothing is kept on an Orcha server today. Model providers may retain prompt data under their own policies. Turning Cloud AI off stops new prompts from being sent to any of them.',
      },
    ],
  },
}

export function blockedPrompt(text: string) {
  const lower = text.toLowerCase()
  if (/\b(csam|child\s*porn|child sexual|sexual(?:ly)? (?:abuse|exploit).*?(child|minor|kid))\b/.test(lower)) return true
  const child = /\b(child|children|kid|kids|minor|minors|underage|preteen|pre-teen|lolita|loli)\b/.test(lower)
  const sexual = /\b(sexual|porn|pornography|nude|nudes|nsfw|explicit sex)\b/.test(lower)
  return child && sexual
}

export function blockedReply() {
  return 'Orcha cannot help with sexual content involving children. If a child is in danger, contact local authorities. You can report this in the thread.'
}
